services:
  - type: web
    name: pineveil-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    plan: free
    region: oregon
    runtime: python
    build:
      pythonVersion: 3.10
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: ADMIN_CHAT_ID
        sync: false
